### ISSUE TITLE
Any Tuya device?

### ISSUE THREAD

**Issue by codeclinic** [razorRun/node-red-contrib-smartlifeair#1]
Does this work with door / window sensors?

**Comment by razorRun** [comment]
Yes

Any device

**Comment by codeclinic** [comment]
Does it also support the newer v3.3 protocol devices?

**Comment by razorRun** [comment]
It should. Give a try and let me know as well. 

use this[ APP](https://www.smartlife.nz/smartlife-air#store-links) and see its working with your device. if its working, node-red part will be ok. Give me a shout if you run into any issues

**Comment by codeclinic** [comment]
To be honest it just looks a bit dodgy. I'll have to give it a miss for now.

**Comment by razorRun** [comment]
Well upto you. Are you talking about the correct app?
