### ISSUE TITLE
Why to turn off the user id used warning?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [razorRun/node-red-contrib-smartlifeair#10]
Why does your node report a successful use of user id?

"User Authenticated as XXXXXX@XXXXX.XXX"  is reported over and over and over.  The constant node.warn() calls reporting which user was authenticated is, frankly, annoying. Is there a way to turn off that notification?  Or how about a feature add, to control the warning?

**Comment by razorRun** [comment]
Actually that was a feature, requested by one of a user with multiple
config accounts. It should happen only on deploy or NR restart. Do you get
this warn in other occasions?

**Comment by Nodi-Rubrum** [comment]
I am seeing it over and over.  Every time I turn on a smart plug, every time I turn off a smart plug.  Every time I toggle the power state of a smart plug, you name it, seems like every action taken, I get a warn notification.

What you intended makes sense, if I edit or change the configuration node, then it should confirmed credential success or failure.  But no when I am just using the device already configured and authenticated.  I am getting 30, 40 or more messages at times, because I am turning on and off like 10 plugs at a time, and more, testing said plugs.

I think a configurable option for this would me cool, let the operator/user turn on or off authorization notification, or drop it into the payload returned... but don't use node.warn() or even node.error() as blind notification.  Moreover, it does not let me handle a bad authentication as a flow processing event, so I could take some action if authentication fails.  For example the catch node can't see it as designed now.

**Comment by Nodi-Rubrum** [comment]
Oh, wait... it does authentication notification PER node?  Right?  That is why I am seeing it over and over.  We have a lot of nodes in one flow.  Still my suggestions still are applicable, make the event, notification. controllable or actionable, would be a great feature/enhancement.

**Comment by razorRun** [comment]
Yep.

Will try to add this once per account. I will have a look what we can do
with NR.

Make sure to give this repo a star if you enjoy using it.

**Comment by Nodi-Rubrum** [comment]
Sure, thanks for being responsive to feedback and suggestions.  Nice work, really like the solution, once I figure it out.  :)

**Comment by razorRun** [comment]
Added this, Try and let me know

**Comment by Nodi-Rubrum** [comment]
Will do!

**Comment by Nodi-Rubrum** [comment]
Nice thanks again.
