### ISSUE TITLE
Any plans to add query comand to the node?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [razorRun/node-red-contrib-smartlifeair#11]
Any plans to add query command to the node?  So a node red flow could get the initial state of the device?

**Comment by razorRun** [comment]
On a startup, it should split up initial state automatically.

**Comment by Nodi-Rubrum** [comment]
Right.  But if I needed or wanted to query state at some future point, the only way to get the state returned is to initiate a command, say power on or off for example.  TUYA API has a request/query call that can retrieve the device state on demand.

**Comment by dachshund-digital** [comment]
Thanks for working on this, greatly appreciated.

**Comment by dachshund-digital** [comment]
Just a friendly nudge on when this might be implemented?

**Comment by razorRun** [comment]
Hey Guys 
I just added this. All you got to do pass string "?" to get the last status. Can you check and let me know

**Comment by razorRun** [comment]
@Nodi-Rubrum do you mind closing this issue after testing this for me. Also, I added a new option to enable disable debug messages. I think you requested it eh ?

**Comment by Nodi-Rubrum** [comment]
Sure, will do!  I will test this tomorrow and it works, close the issue.  Thanks for adding this!

**Comment by Nodi-Rubrum** [comment]
Just tested it, sorry took me a few days to get to this.  Works fine, passing '?' returned the state of the device.  Thanks!  This lets me setup a NR flow that can scan the devices to get their active state.  Nice.

**Comment by Nodi-Rubrum** [comment]
Closing issue.
