### ISSUE TITLE
Nooie plugs no inputs

### ISSUE THREAD

**Issue by Robo1112** [razorRun/node-red-contrib-smartlifeair#13]
Hey,

at first - I've read all previously submitted issues about the error message "No available inputs".

But any of the posted fixes did worked for me. I have a NZ account and my other LED stripe is working fine. So the account must be correctly.

Also I updated the firmware of the nooie plug to newest version (1.0.5).

From the Smart Life App I'm able to control the socket without any problems. But from your beautiful Node-RED-Node it doesn't work. All times it says "No available inputs" ...

Please help me! These are the plugs:
https://www.amazon.de/Steckdose-Fernbedienbar-Sprachsteuerung-Funktion-Kompatibel/dp/B07V26TJ58

Best Regards
Robin

**Comment by Robo1112** [comment]
Thank your for your answer.

As you expected already, it didn't worked for me ...

Best Regards
Robin

**Comment by razorRun** [comment]
But I usually use a way around it by setting up an automation rule in the
app

Example
You can turn this light on when the other light come on
