### ISSUE TITLE
Not getting output from device-node node now?

### ISSUE THREAD

**Issue by dachshund-digital** [razorRun/node-red-contrib-smartlifeair#15]
Really weird, notice this morning device-node node in node red is turning smart plug on and off, but the device-node is never sending anything to output?

Using Raspberry Pi 10 (Buster) fully patched
Node Red 1.1.3
NPM 6.14.8
Node 12.19.0

If I do any change to the given flow, do a deployment, THEN, some output results BUT if is bad data, wrong state of smart plug, wrong values. For example, switch value is ALWAYS reported as FALSE, when the smart plug is actually ON or true value is expected.

`[{"id":"f22d6f02.88a19","type":"debug","z":"a930fbaf.0652b8","name":"Message","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1640,"y":1440,"wires":[]},{"id":"817cdc10.242a1","type":"inject","z":"a930fbaf.0652b8","name":"Off","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":1110,"y":1460,"wires":[["196e415d.0bd77f"]]},{"id":"16657021.e096f","type":"inject","z":"a930fbaf.0652b8","name":"On","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":1110,"y":1420,"wires":[["196e415d.0bd77f"]]},{"id":"196e415d.0bd77f","type":"device-node","z":"a930fbaf.0652b8","name":"Black Lasko Fan Power Control (Awow 163)","account":"[redacted]","selectedDevice":"[redacted]","selectedInput":"switch_1","selectedOutput":"root","outputConversion":"false","x":1370,"y":1440,"wires":[["f22d6f02.88a19"]],"icon":"font-awesome/fa-power-off"},{"id":"[redacted]","type":"smartlifeair-login","z":"","email":"[redacted]","password":"[redacted]"}]`

Also, have you figured out how to optionally surpress all the node.warn() for authentication messages? That is really getting annoying.

**Comment by razorRun** [comment]
I am working on an update on my free time. Will have a look at this 
Cheers

**Comment by dachshund-digital** [comment]
Thanks man, let me know if I can help in any way.  :)

**Comment by razorRun** [comment]
Are you still see this behaviour

**Comment by Nodi-Rubrum** [comment]
Looks like things are working as expected again!

So, any update on the following requested features?
1) Ability to query on demand state of device, i.e. get switch state?  Maybe just add another node type of the solution?
2) Ability to suppress the authentication warnings?

#1 Above I think everyone would use and appreciate.  Definitely would love this feature to be added to the solution.
#2 Above, just something I would like to be able to do, not sure if is that big a deal for others

**Comment by razorRun** [comment]
Sorry mate, I have been tide to million things these days. Leave the two tickets, I should be able to get to these probably next weekend

**Comment by Nodi-Rubrum** [comment]
No worries... not urgent.  I know you will do what you can when you can.  :)
