### ISSUE TITLE
Authentication error after Node-RED restart

### ISSUE THREAD

**Issue by cymplecy** [razorRun/node-red-contrib-smartlifeair#19]
Yesterday, I restarted my Node-RED install and now I'm getting
![image](https://user-images.githubusercontent.com/2357428/101238045-7263a900-36d5-11eb-97cf-0fedf899ea6b.png)

**Comment by cymplecy** [comment]
Having created another account and that not working then switching back to original account, turning around 3 times, switchign everything off and on again 4 times and sacrifing a small sheep - its back working

**Comment by razorRun** [comment]
I noticed this issue few days back. I think this happens when nod red boot
up before node code talks to the internet. Till I add a retry mechanism,
please add a node red service restart after 2-3 mins on @reboot of the
device.

**Comment by razorRun** [comment]
@cymplecy I just added an Authentication retry method, Can you please test this and let me know how it goes?
