### ISSUE TITLE
Door sensor supported?

### ISSUE THREAD

**Issue by malosaa** [razorRun/node-red-contrib-smartlifeair#21]
First of all great plugin.

I added the door sensor correctly but no input or output.

how can i use it for status? because if i close the door or open it works on the app but nothing happens on node-red

Firmware version 1.0.4 
and from smart led 6.0.4 

no firmware available.

// 
aswell for my smart led e27 same thing

regards

**Comment by razorRun** [comment]
did you create the account in using a US regional country as instructed? also you need to deploy after selecting devices.
