### ISSUE TITLE
Need instructions on options available

### ISSUE THREAD

**Issue by peliopoulos** [razorRun/node-red-contrib-smartlifeair#22]
Thanks for all your work on this project.  I really appreciate that you have put this together!

I have a "Bright"-branded plug that I want to be able to turn off using Node-Red triggered by a command from Join.  However, the inputs and outputs are not clear and don't seem to affect the LED/power state of the plug:

**Input options (while device is on):**
switch_1 ==> Values:Boolean
countdown_1 ==> Values:Integer ("unit":"s","min":0,"max":86400,"scale":0,"step",1)

**Output options**
countdown_1 ==> Value:0
switch_1 ==> Value:true
All Output Channels as a JSON

I have tried lots of combinations and none of them change the status of the plug.  What do I select?  Does the output from the Join command matter?

Thanks in advance

**Comment by razorRun** [comment]
What happens when you connect a debug node to output and select JSON? Also,
can you share your device ID?

**Comment by peliopoulos** [comment]
my device ID is 58776028d8f15bc474bd

The output is :

```
countdown_1: 0
switch_1: false
```

**Comment by razorRun** [comment]
Does this emit again and again when you press something on the plug? And
can the plug be operated from the mobile app?

**Comment by peliopoulos** [comment]
Yes, when I turned the plug on, the output changed switch_1 to true one time. And then again to false when I turned off the plug.

The app controls the switch with no issues.

**Comment by razorRun** [comment]
Ok so that's mean output is working correctly Isn't it?

For the input select switch 1 and send just a boolean value

**Comment by razorRun** [comment]
Just try with 2 inject nodes with true and false.
Connect them to the node input and select switch_1 and deploy and press
those inject buttons

**Comment by peliopoulos** [comment]
My input was the problem, thanks for helping me troubleshoot it!  Now I just need to get Join to spit out a Boolean value.

For troubleshooting purposes, I used the **Inject** node, Payload type to **boolean** and value of **true**.  I also turned on the "Inject once after **60** seconds" option to allow for the SmartLife to login.

**Comment by razorRun** [comment]
Can you see if your NR system log spit out any errors on startup?

Also this could be because switch_1 is controlling something not visible.

Check this
https://github.com/razorRun/node-red-contrib-smartlifeair/issues/16

**Comment by peliopoulos** [comment]
Everything is working perfectly now, thanks so much!  

I have my phone using Tasker to send a Joaoapps Join messages to Node-Red.  I use a function to process the Join message to a True or False value which feeds to the SmartLife Air nodes.  In turn, the plugs are turned on or off.

**Comment by razorRun** [comment]
Awesome, thanks!

Btw what did you change to fix it?

**Comment by peliopoulos** [comment]
I wasn't feeding it a boolean value correctly.  Once I fixed that, it worked fine, then just a matter of turning my trigger into boolean.
