### ISSUE TITLE
Battery level output from TRV

### ISSUE THREAD

**Issue by DrDuk** [razorRun/node-red-contrib-smartlifeair#24]
Is it possible to retrieve the battery state from the Tuya radiator valve controllers (HY368-ZB Tuya ZigBee 3.0 Smart Radiator Actuator Programmable Thermostatic Radiator) either as a single output option or as part of the full JSON output? Thanks

**Comment by razorRun** [comment]
If it has a data node for that it should work. But I don’t have any
experience with this particular device

Cheers

**Comment by DrDuk** [comment]
I can't tell if there is a data node for this.  Here is the output I receive for the JSON object:

{"Auto_Lock":false,"Days_Holiday":1,"Prog_Restday":"################","Prog_Workday":"################","Temp_holiday":15,"boost":300,"child_lock":false,"comfort_temp":20,"eco_temp":15,"fault":0,"hightemp":35,"lowtemp":5,"mode":"manual","power_state":false,"roomtemp_calibrat":20,"temp_current":215,"temp_set":220,"valve":100,"valve_set":"normal","week_state":"0","wind":"AAUK","windows_state":false}

Nothing looks like a battery value.  It is a bit weird that they give you everything else but the battery status.
Thanks

**Comment by razorRun** [comment]
Unfortunately you can only read what you have in above object. Does the app
shows you a battery value?
