### ISSUE TITLE
Another device with missing inputs/outputs

### ISSUE THREAD

**Issue by koshisan** [razorRun/node-red-contrib-smartlifeair#26]
Hi,

thanks for the great work! I just bought a light which can be controlled through the SmartLife Air App. After setting everything up the device is listed in the node-red configuration, but no channels turn up.

I can refresh, but that doesn't change anything :/

There is no firmware update available according to the app which is - no doubt - due to the strangeness of my device: It's a "Smart Wi-Fi Music Star Light"...

The ID is c1bc05ee1413f363 - can we get it working even though it is not a "common" light bulb? I don't care for the music functions, but the on-off/color selection functionality seems to mimic a normal LED bulb...

**Comment by razorRun** [comment]
https://github.com/razorRun/node-red-contrib-smartlifeair/issues/16
