### ISSUE TITLE
No Channels for Shutter switch

### ISSUE THREAD

**Issue by mupsje** [razorRun/node-red-contrib-smartlifeair#28]
Hi, Please can you fix the shutters.

thanks

![image](https://user-images.githubusercontent.com/46684538/112948063-dfdd8e80-9137-11eb-8165-5f7d96055437.png)

Mupsje

**Comment by razorRun** [comment]
Please read the older issue that talk about no inputs

**Comment by razorRun** [comment]
https://github.com/razorRun/node-red-contrib-smartlifeair/issues/16
