### ISSUE TITLE
Send ? And Configured for JSON (all values), the state is wrong, but via the UI, the state is correct?

### ISSUE THREAD

**Issue by dachshund-digital** [razorRun/node-red-contrib-smartlifeair#29]
Send ? And Configured for JSON output (all values), the state is wrong, but via the NR UI, the state is correct?  Send ? and Configured for Switch_1 value as output, the state is incorrect. but the NR UI view shows correct state.

Reference the graphic below, the left red circle shows the correct state of the smart plug.  The red circle on the right, shows the payload output for all channels, and the state is true, which is incorrect. 

![SmartLife Air Node Error](https://user-images.githubusercontent.com/1486285/113080887-7f2c7100-918c-11eb-99ff-8e003ca6acc9.png)

Using NR 1.2.9 and SmartLife Air Node 1.0.11.
.

**Comment by razorRun** [comment]
Took bit of time to understand what you meant, I suppose you are talking
about sending “?” To get feedback eh?

How that work is it will send you whatever the last state it get to the
node. And on the startup it takes around 10-15s to authenticate and emit
the first status. So I would suggest wait 15sec or so for the first state
update

Cheers

**Comment by dachshund-digital** [comment]
Ah.  So what I see immediately on node start up (after deploy or NR restart) isn't valid.  That also seems to explain why if I send an explicit command, the result returned is valid... it triggers an update.  Thanks for the timely response, appreciate it.

**Comment by razorRun** [comment]
You are welcome.

If you find this node useful make sure to drop a star to increase
visibility. Coz we need to find a couple of people to maintain this repo.

Cheers

**Comment by dachshund-digital** [comment]
Oh, dang thought this was already closed.
