### ISSUE TITLE
No available inputs

### ISSUE THREAD

**Issue by Andobi** [razorRun/node-red-contrib-smartlifeair#3]
Managed to get the device to show up in node red. When adding the node, I see "No available inputs" in the dropdown boxes for both the input and output selections. So it seems I'm unable to do anything with it.

The device id shows up in the device dropdown as fed0189a574c5a47. I've set it up as a wifi dimmer switch in the smartlife air app, and the app controls it as expected. It's actually not that slow if it thinks it is in NZ instead of UK.

**Comment by Andobi** [comment]
Any update on this?

**Comment by follower46** [comment]
I had this same problem today. I was able to get the inputs working again by removing and re-adding my credentials.

**Comment by razor1331** [comment]
Sorry Guys I am bit packed these days. I will look into this on the weekend.

Cheers

**Comment by Andobi** [comment]
> I had this same problem today. I was able to get the inputs working again by removing and re-adding my credentials.

This didn't work for me. Did you have to restart node red in between?

**Comment by follower46** [comment]
No, I didn't have to restart the service. I did have to deploy between removing and readding.

**Comment by Andobi** [comment]
I decided to try adding a bulb to this app. Actually with the bulb a bunch of options popped up, so I guess it is not configured to work with my wall dimmer switch. Can this be added?

**Comment by razorRun** [comment]
Can you please try updating the firmware from smartlife air app ?

**Comment by Andobi** [comment]
No update available.

**Comment by razorRun** [comment]
Can you send me the device ID?

**Comment by Andobi** [comment]
Can't seem to find a PM option, do you want this by email?

**Comment by razorRun** [comment]
Might as well.

**Comment by Andobi** [comment]
Can follow up here. Pressed button as requested.

**Comment by razorRun** [comment]
I have manually added the reference for now ebb*****, but usually virtual
ID on the app should be same as the node red one.

You might have to close the nodered node to see it, can you check and let
me know? ( Dont press the refresh button

**Comment by Andobi** [comment]
I can see a third device there with inputs and outputs so I guess this has worked.

Can you explain what has happened here? I've tried to look through your code but it's pretty complicated without much Javascript knowledge so I haven't got a clue how it works.

**Comment by razorRun** [comment]
For some reason your device ebb5***** can not be founded under your devices
on your Smartlifeair account (r****r@****m) it might have been a enrollment
issue. Also I need to find some time to iorn out the bugs... At the moment
I am fully packed.. But I will try to attend to these probably sometime
next week


Cheers

**Comment by Andobi** [comment]
That's great. It does appear I can control the device now. You could do with some more documentation, it took a little while to figure out what payload I should send.

I'd also appreciate an explanation of how this works. It sounds like you have set up your own cloud somehow.

**Comment by Andobi** [comment]
I've just tried to add a new node to another flow and the id you manually added has disappeared. Is there a way I can enrol the device again?

**Comment by razorRun** [comment]
Ll do.
Love to get some help it as well.

If you get a chance can you please do a short video/screen capture( may be
a gif) of the enrollment process from account creation to the getting
devices to node red dropdown, will help lot of people who are having issues
following exact steps. I will link it to the read me as well

Cheers

**Comment by razorRun** [comment]
Might as well try to debug and fix the issue while I am online, can you remove that device and refresh the account.  
And re add and let me know how it goes?

Also send me a console log of  https://smartlife-air-plugins.smartlife.nz <https://smartlife-air-plugins.smartlife.nz/>

**Comment by Andobi** [comment]
Apologies, a rare occurrence of my internet dropping out. Will look at this again tomorrow.

**Comment by Andobi** [comment]
> Might as well try to debug and fix the issue while I am online, can you remove that device and refresh the account. And re add and let me know how it goes? Also send me a console log of https://smartlife-air-plugins.smartlife.nz <https://smartlife-air-plugins.smartlife.nz/>

I've followed these steps, seems we are back where we started. The device id showing in node red is not the same as the virtual id in the app. Looks like that virtual id is the same as before, starting ebb***.

Not sure what you mean by console log, the message in the blue box at the bottom reads (anonymised):

> You have enrolled following devices
=>>{ "fed***": [culprit device], "607***": [another device] }

**Comment by razorRun** [comment]
I will roll out an update to fix this issue
