### ISSUE TITLE
FYI... New plugs will not connect via normal mode setup or paired mode setup, when connecting to device AP, get password prompt?

### ISSUE THREAD

**Issue by dachshund-digital** [razorRun/node-red-contrib-smartlifeair#32]
FYI... New plugs will not connect via normal mode setup or paired mode setup, when connecting to device AP, get password prompt?  So they have an embedded PSK key maybe?  I got one of the plugs to connect and setup with their official application.  But the official app does not show much information about the plug.  They also do not show up as 'SmartLife_XXX' but a different randomized string it appears.   The official app is 'Cloud Intelligence'.  I did notice the default device name on the network started with ESP_ so they appear to be some variant of ESP device.  Box lists the device type as YX-WS01, which I have added to SmartLife Air before in the past.  Figure these could yet another newer tuya generation of firmware?

**Comment by razorRun** [comment]
Goes it work with tuya app?

**Comment by dachshund-digital** [comment]
Trying the 'tuya smart' app now.

**Comment by dachshund-digital** [comment]
Nope auto scan, manually never seems to find the device, but I can see it in the AP list.  So I tried pairing mode under tuya, still no joy.  Only app that seems to work is the official app for these plugs, the "Cloud Intelligence" app.  So either these are not ESP based, but the network name starts with ESP so implies they are.  Pairing attempt I see an odd name, for AP mode, that does not start with the typical 'SmartLife_XXX' format.  And in pair mode on your app, I can't get the device to do slow blink state.

**Comment by razorRun** [comment]
Hey
Then probably these devices are running their own firmware but still based
on esp chip. You should be able burn a esp firmware. But probably won’t
worth the effort
Cheers

**Comment by dachshund-digital** [comment]
Yeah, I would have to crack them open to confirm, and if no ESP, but Reltek then that would be its own PITA.  I am going to return them and get some that are either open API, Tasmota flashed, or such.
