### ISSUE TITLE
Reset Password in https://smartlife-air-plugins.smartlife.nz/login

### ISSUE THREAD

**Issue by denyz427** [razorRun/node-red-contrib-smartlifeair#36]
Registered in https://smartlife-air-plugins.smartlife.nz/login with mistyped password, now I don't know what my password is and it said "Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later." 
What should I do to reset my password in https://smartlife-air-plugins.smartlife.nz/login? There is no forgot password button, only red Register Account text that do nothing. 

![image](https://user-images.githubusercontent.com/84823943/119592580-f421cd00-be02-11eb-8d7d-dec2b0058a74.png)

**Comment by razorRun** [comment]
Please check your email for password reset

**Comment by denyz427** [comment]
I am sorry for not telling you this, but the email account that I want to
reset password is ***@***.***

**Comment by denyz427** [comment]
Thank you for your help ^^
