### ISSUE TITLE
Can't sign in to app

### ISSUE THREAD

**Issue by peliopoulos** [razorRun/node-red-contrib-smartlifeair#38]
My wife got a new phone and when I tried to log in to her account, I get a "Incorrect Account ID or password" message.  I double checked and have the right app (https://play.google.com/store/apps/details?id=com.smartlifelabs.smartlifeair) and was able to log in to the web portal without issue.

peliopoulos@gmail.com

**Comment by razorRun** [comment]
Hey

Try Reseting the password and set the same password back

Cheers

**Comment by yasurok** [comment]
> Hey Try Reseting the password and set the same password back Cheers

I've had the same issue with @peliopoulos, and I am happy to report @razorRun's solution worked for me as well --- as ridiculous as it may sound. They did not reject the same password or anything.

**Comment by peliopoulos** [comment]
it worked, although I could only do it in the app, would be nice to do it in the website too.  Thanks @razorRun and @yasurok !
