### ISSUE TITLE
Every time I login to  https://smartlife-air-plugins.smartlife.nz/ it kicks me back out in about 10 seconds:: Fixed Now - See instructions 

### ISSUE THREAD

**Issue by Nodi-Rubrum** [razorRun/node-red-contrib-smartlifeair#6]
Every time I login to  https://smartlife-air-plugins.smartlife.nz/ it kicks me back out in about 10 seconds.  I was able to create the account, register it.  Was able to download the app on my phone, and setup 1 device on it.  It works.  But every time I try to set the country code via login to  https://smartlife-air-plugins.smartlife.nz/ it kicks me back out in about 10 seconds.  What the heck?

**Comment by Cesarsanf** [comment]
Same thing happening to me, actually my Flows running this Node stopped working a few days ago.

I noticed I was running version 0.15 and current one was 0.45. Update failed, so I have removed my account uninstalled and then I was able to reinstall the latest version.

But any of my devices appeared to me after the reinstall, I've created a new account, associated my devices but I when I login to https://smartlife-air-plugins.smartlife.nz/ I am kicked out... 

And same thing on this new account, no devices available.

Any help, please?

**Comment by razorRun** [comment]
Hey
Sorry tried to replicate what you guys are experiencing, so far without any
luck. So I am going to need bit of help with diagnosing the problem.

What’s the country you choose when you register in the mobile app ?

**Comment by razorRun** [comment]
And also can you please check the web app version. Latest should be v1.0.5.
Clear the browser cache and let me know?

**Comment by Cesarsanf** [comment]
I have one account with Brasil selected and other with USA, any of them working.

I ve tried in 3 different browsers, 2 differenct PCs, cleared the cache and nothing... 

My version of Smartlife Air is 1.0.0 but it says its the latest.

**Comment by razorRun** [comment]
Sorry I meant to say web app version.

Just deployed a new version on the web app. It should be 1.0.6 now. Can you
try again?

**Comment by Cesarsanf** [comment]
Now I was able to login and stay connected, but when I try to Set and refresh, it says Permission denied!

**Comment by razorRun** [comment]
Found the issue 
@Cesarsanf I have deleted your Gmail account for now. Working on a fix now. Please signup to the web app again once I apply the patch. I will inform you in a few mins.

**Comment by Cesarsanf** [comment]
Awesome! Everything working now!

Thanks a lot!!

**Comment by razorRun** [comment]
Happy to help. Don't forget to give us a star if you are happy with the package.

And **For the people who registered in last few days please create a new account on the mobile app and web app**
Cheers

**Comment by Nodi-Rubrum** [comment]
Yeah, I can test too, as needed.  I guess you will need to delete my account as well?

**Comment by razorRun** [comment]
Do you mind flicking your email ?
