### ISSUE TITLE
Alexa does not work in EU with connection to US DB

### ISSUE THREAD

**Issue by ammawel** [razorRun/node-red-contrib-smartlifeair#7]
In order to get "node-red-contrib-smartlifeair" to work here in Germany, I chose an account in New Zealand as described during the registration in the app.
Everything works fine; Tuya WiFi lamps can be switched and dimmed via node-red and MQTT.

But the control via Alexa does not work anymore.
The Smartlife-Skill of an Amazon account in EU does not recognise the Smartlife-Air account in NZ.
When I create an account in Germany during registration in the Smartlife app, the skill connects, Alexa works fine, but node-red does not find any devices anymore.

Switching the entire Amazon account to NZ is not a solution, as other services will not work.

Any hints?

Thanks
Achim

**Comment by razorRun** [comment]
Hey Achim 

Smartlife skill should work, but probably the issue is the data region. Please see the readme. I think you have to options, create amazon account in same region( see list of countries in the readme). Or use node red Alexa node and link them to your smartlife air items in node red

**Comment by sniicker** [comment]
I have a new zealand account and a german alexa account  - no problem erverything works fine
