### ISSUE TITLE
No inputs or outputs available 

### ISSUE THREAD

**Issue by pinpox** [razorRun/node-red-contrib-smartlifeair#8]
Hello! 

I have created a account and added it in node-red, it currently has 2 wifi switches registered which I can control via the smartlife air app and show up in https://smartlife-air-plugins.smartlife.nz/home as
```
You have enrolled following devices:
303167bb252ae578: "Wi-Fi Smart Switch 2"
ee8665a4067ab5f2: "Wi-Fi Smart Switch"
```
In node-red I can select the device, but there are **no inputs and outputs**:
![image](https://user-images.githubusercontent.com/1719781/92799556-2d6cf680-f3b4-11ea-9af6-b18c30ded492.png)

I have operated the device several times in the app and tried deploying and deleting and adding the devices again, but I can't get around the bug. Any idea what is going wrong or how to fix it?

I can provide any information you need to get this fixed, just let me know!

**Comment by razorRun** [comment]
Did you try updating the firmware. The thing is some device manufacturers uses customised com patterns which does not support regular api. Unfortunately in this case only thing you can do is first try updating the firmware and refreshing channels.

**Comment by jschaeke** [comment]
Same problem here with some wifi plugs from Aliexpress... can't get it updated in Tuya or Smartlife Air as they're on the latest.

**Comment by razorRun** [comment]
Have a read on this issue
https://github.com/razorRun/node-red-contrib-smartlifeair/issues/16
