### ISSUE TITLE
Account setup, and device shows under account on website and in smart app, but in node red select device list is empty?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [razorRun/node-red-contrib-smartlifeair#9]
Account setup, and device shows under account on website and in smart app, but in node red select device list is empty?  I did get the account id in node red when I added credentials used in web site.  Web site does show 1 device added, with same name as device in phone app.  Not sure what to try or do next?

**Comment by razorRun** [comment]
Did you deploy after adding the credentials in nodered?

**Comment by Nodi-Rubrum** [comment]
Yup, I had to generate the initial event, that got the list to refresh, and all was fine after that.  Thanks for the quick response and assistance.

**Comment by razorRun** [comment]
Thanks


If you are happy with the node don't forget to give it a star 💫
